version: '1.0.0'

services:
    nginx:
        restart: always
        image: nginx:1.25.2-alpine
        platform: linux/amd64
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/cork/django_static
    server:
        restart: unless-stopped
        platform: linux/amd64
        build:
            context: .
            dockerfile: ./docker/cork/Dockerfile
        entrypoint: /app/docker/cork/server-entrypoint.sh
        volumes:
            - static_volume:/app/cork/django_static
            - dev_volume:/app/cork
        expose:
            - 8000
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
            CELERY_RESULT_BACKEND: "redis://redis:6379/0"
            DJANGO_DB: postgresql
            POSTGRES_HOST: db
            POSTGRES_NAME: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_PORT: 5432
        depends_on:
            - db
            - redis
    worker:
        restart: unless-stopped
        platform: linux/amd64
        build:
            context: .
            dockerfile: ./docker/cork/Dockerfile
        entrypoint: /app/docker/cork/worker-entrypoint.sh
        volumes:
            - static_volume:/app/cork/django_static
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
            CELERY_RESULT_BACKEND: "redis://redis:6379/0"
            DJANGO_DB: postgresql
            POSTGRES_HOST: db
            POSTGRES_NAME: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_PORT: 5432
        depends_on:
            - server
            - redis
            - db
    redis:
        restart: unless-stopped
        image: redis:7.2.1-alpine
        platform: linux/amd64
        expose:
            - 6379
    db:
        image: postgres:16.0-alpine
        platform: linux/amd64
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        expose:
            - 5432


volumes:
    static_volume: {}
    postgres_data: {}
    dev_volume: {}